name = "cf-redirect-worker"
main = "src/index.js"
compatibility_date = "2024-06-27"
account_id = "ba6fe5593eb84270b4303c34ac7e9d26"
workers_dev = false

route = "茶妹.co/*"
zone_id = "4bed5ebab18d456a38026c4fc460ba8e"

kv_namespaces = [
  { binding = "ChaMei", id = "72eedfdca52a4c40ba5674dcf1c13750" }
]
