name = "cf-redirect-worker"
main = "src/index.js"
compatibility_date = "2024-06-27"
account_id = "你的 Cloudflare 账户 ID"
workers_dev = false

route = "茶妹.co/*"
zone_id = "你的 Zone ID"

kv_namespaces = [
  { binding = "ChaMei", id = "你的 KV 命名空间 ID" }
]
